# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='logo',
            field=models.ImageField(default='', upload_to='extensions/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
