# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models

import apps.extensions.utils


class Migration(migrations.Migration):
    dependencies = [
        ('extensions', '0002_extension_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='source',
            field=models.ImageField(default='', upload_to=apps.extensions.utils.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extension',
            name='logo',
            field=models.ImageField(upload_to=apps.extensions.utils.get_upload_path),
        ),
    ]
