# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models

import apps.extensions.utils


class Migration(migrations.Migration):
    dependencies = [
        ('extensions', '0003_auto_20170425_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='version',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extension',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='extensions', to='extensions.Category'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.extensions.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='extension',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='extensions', to='auth.Group'),
        ),
    ]
