# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 10:28
from __future__ import unicode_literals

import apps.extensions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0005_auto_20170425_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='source',
            field=models.FileField(upload_to=apps.extensions.models._get_upload_path),
        ),
    ]
