# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_auto_20170427_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
