# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extensions', '0009_extension_imports_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='imports_path',
            field=models.URLField(default='imports/'),
        ),
    ]
