# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_auto_20170501_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
