# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.CharField(default='en-us', max_length=20),
        ),
    ]
