# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepik_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepikuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='StepikUser',
        ),
    ]
