# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170422_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepikuser',
            name='access_token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stepikuser',
            name='refresh_token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stepikuser',
            name='server',
            field=models.URLField(default='https://stepik.org/'),
        ),
        migrations.AlterField(
            model_name='stepikuser',
            name='userid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
