# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170422_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepikuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='StepikUser',
        ),
    ]
