# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170422_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='user_groups',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
    ]
